kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pv
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mysql
  labels:
    app: wordpress
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        ports:
          - containerPort: 3306
            protocol: TCP
            name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysqlvolume
        env:
        - name: "MYSQL_ROOT_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: "MYSQL_DATABASE"
          value: "sample"
        - name: "MYSQL_USER"
          value: "mysql"
        - name: "MYSQL_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
      volumes:
      - name: mysqlvolume
        persistentVolumeClaim:
          claimName: mysql-pv